### ISSUE TITLE
unknown argument: '--disable-sandbox' in homebrew

### ISSUE THREAD

**Issue by matanelgabsi** [yonaskolb/SwagGen#56]
Hi there,
I'm getting:
<unknown>:0: error: unknown argument: '--disable-sandbox'
after running:
brew tap yonaskolb/SwagGen https://github.com/yonaskolb/SwagGen.git
brew install SwagGen

This is due to the command:
swift --disable-sandbox build -c release -Xswiftc -static-stdlib

swift -version output:
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

xcode version 9.2

Any idea why?
Thank you!

**Comment by yonaskolb** [comment]
Interesting. Works for me here.
If you run `xcode-select -p` does it point to your Xcode 9.2 install?

**Comment by matanelgabsi** [comment]
Yes:
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by yonaskolb** [comment]
Strange. Does the same thing happen if you checkout this repo and run `make`?

**Comment by yonaskolb** [comment]
Ahh I see the issue. One sec, I'll commit a fix

**Comment by yonaskolb** [comment]
Fixed here https://github.com/yonaskolb/SwagGen/commit/cc7f6543a9470815206668ea2be31dfcd09410e3

**Comment by matanelgabsi** [comment]
Command has changed to: swift --disable-sandbox -c release -Xswiftc -static-stdlib
but still having issues:
==> Building SwagGen
==> swift --disable-sandbox -c release -Xswiftc -static-stdlib
Last 15 lines from /Users/matanelgabsi/Library/Logs/Homebrew/SwagGen/01.swift:
2017-12-25 16:52:09 +0200

swift --disable-sandbox -c release -Xswiftc -static-stdlib

<unknown>:0: error: unknown argument: '--disable-sandbox'
<unknown>:0: error: unsupported option '-c' for 'swift'; did you mean 'swiftc -c'?

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
yonaskolb/swaggen

**Comment by yonaskolb** [comment]
Should be fixed now 👍 
Sorry, wasn't paying proper attention - it's Christmas :)

**Comment by matanelgabsi** [comment]
haha 👍 
Works now, Thanks!

By the way, great project! loved it! using it for a while now :)

**Comment by yonaskolb** [comment]
Thank you! Glad you're getting some good use out of it 😄
